version: 2.1
jobs:
    build:
        docker:
            - image: nightscape/scala-mill
        steps:
            - checkout
            - run:
                name: Test (2.11.8, 2.3.0)
                command: mill "spark-constraints[2.11.8,2.3.0].test"
            - run:
                name: Test (2.11.8, 2.4.0)
                command: mill "spark-constraints[2.11.8,2.4.0].test"
            - run:
                name: Test (2.12.4, 2.4.0)
                command: mill "spark-constraints[2.11.8,2.4.0].test"
